# Generated by Django 4.0 on 2023-07-02 14:05

from django.db import migrations

from django.contrib.auth.models import Group, Permission
from django.db import migrations

from appauth.models import EmployeeUser

GROUP_PERMISSIONS = {
    'admin': [
        ('add_manager', 'Can add manager'),
        ('delete_manager', 'Can delete manager'),
        ('add_employee', 'Can add employee'),
        ('delete_employee', 'Can delete employee'),
        # Add more permissions for the 'admin' group
    ],
    'manager': [
        ('add_employee', 'Can add employee'),
        ('delete_employee', 'Can delete employee'),
        # Add more permissions for the 'manager' group
    ],
    'employee': [
        # Add permissions for the 'employee' group
    ],
}


def create_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for group_name, permissions in GROUP_PERMISSIONS.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        for permission_codename, permission_name in permissions:
            content_type = ContentType.objects.get_for_model(EmployeeUser)
            permission, _ = Permission.objects.get_or_create(
                codename=permission_codename,
                content_type=content_type,
                defaults={'name': permission_name}  # Set the name of the permission
            )
            group.permissions.add(permission)
            
def remove_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    for group_name in GROUP_PERMISSIONS.keys():
        Group.objects.filter(name=group_name).delete()

    Permission.objects.filter(codename__in=[perm[0] for perm_list in GROUP_PERMISSIONS.values() for perm in perm_list]).delete()
            

class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions, reverse_code=remove_groups_and_permissions),
    ]
